@extends('layouts.admin')
@section('title','Tampilan Web')
@section('page-title','Tampilan Web')
@section('page-description','Atur konten yang dilihat customer tanpa mengubah kode.')
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
<div class="admin-tabs" data-tabs><button class="active" data-tab="banner">Banner</button><button data-tab="featured">Produk Unggulan</button><button data-tab="profile">Profil Usaha</button><button data-tab="payment">Pembayaran</button><button data-tab="social">Media Sosial</button></div>
<section class="admin-card tab-panel active" data-panel="banner"><h2>Banner Beranda</h2><form method="POST" action="{{ route('admin.appearance.hero') }}">@csrf @method('PATCH')<div class="form-grid"><div class="form-group full"><label>Judul</label><input name="title" value="{{ old('title',$hero['title'] ?? '') }}" required></div><div class="form-group full"><label>Subjudul</label><input name="subtitle" value="{{ old('subtitle',$hero['subtitle'] ?? '') }}" required></div><div class="form-group"><label>Label tombol</label><input name="cta_label" value="{{ old('cta_label',$hero['cta_label'] ?? '') }}" required></div></div><button class="button button-primary">Simpan Banner</button></form></section>
<section class="admin-card tab-panel" data-panel="featured"><h2>Produk Unggulan</h2><p class="muted">Pilih maksimal delapan produk aktif untuk ditampilkan di beranda.</p><form method="POST" action="{{ route('admin.appearance.featured') }}">@csrf @method('PATCH')<div class="featured-select">@foreach($products as $product)<label><input name="products[]" value="{{ $product->id }}" type="checkbox" @checked(in_array($product->id, $featuredProductIds, true))><span class="table-thumb tone-{{ $product->tone }}"></span>{{ $product->name }}</label>@endforeach</div><button class="button button-primary">Simpan Produk Unggulan</button></form></section>
<section class="admin-card tab-panel" data-panel="profile"><h2>Profil Usaha</h2><form method="POST" action="{{ route('admin.appearance.business') }}">@csrf @method('PATCH')<div class="form-grid"><div class="form-group"><label>Nama usaha</label><input name="business_name" value="{{ old('business_name',$business['business_name'] ?? '') }}" required></div><div class="form-group"><label>WhatsApp</label><input name="phone" value="{{ old('phone',$business['phone'] ?? '') }}" required></div><div class="form-group full"><label>Alamat</label><textarea name="address" rows="3" required>{{ old('address',$business['address'] ?? '') }}</textarea></div><div class="form-group"><label>Jam operasional</label><input name="opening_hours" value="{{ old('opening_hours',$business['opening_hours'] ?? '') }}" required></div><div class="form-group"><label>Google Maps</label><input name="maps_url" value="{{ old('maps_url',$business['maps_url'] ?? '') }}" placeholder="https://maps.google.com/..."></div></div><button class="button button-primary">Simpan Profil</button></form></section>
<section class="admin-card tab-panel" data-panel="payment"><h2>Informasi Pembayaran</h2><form method="POST" action="{{ route('admin.appearance.payment') }}">@csrf @method('PATCH')<div class="form-grid"><div class="form-group"><label>Nama bank</label><input name="bank_name" value="{{ old('bank_name',$payment['bank_name'] ?? '') }}" required></div><div class="form-group"><label>Nomor rekening</label><input name="account_number" value="{{ old('account_number',$payment['account_number'] ?? '') }}" required></div><div class="form-group full"><label>Nama pemilik</label><input name="account_name" value="{{ old('account_name',$payment['account_name'] ?? '') }}" required></div><div class="form-group full"><label>Catatan QRIS</label><input name="qris_note" value="{{ old('qris_note',$payment['qris_note'] ?? '') }}"></div></div><button class="button button-primary">Simpan Pembayaran</button></form></section>
<section class="admin-card tab-panel" data-panel="social"><h2>Media Sosial</h2><form method="POST" action="{{ route('admin.appearance.social') }}">@csrf @method('PATCH')<div class="form-grid"><div class="form-group"><label>Instagram</label><input name="instagram" value="{{ old('instagram',$social['instagram'] ?? '') }}" placeholder="https://instagram.com/..."></div><div class="form-group"><label>TikTok</label><input name="tiktok" value="{{ old('tiktok',$social['tiktok'] ?? '') }}" placeholder="https://tiktok.com/@..."></div><div class="form-group"><label>YouTube</label><input name="youtube" value="{{ old('youtube',$social['youtube'] ?? '') }}" placeholder="https://youtube.com/@..."></div><div class="form-group"><label>Facebook</label><input name="facebook" value="{{ old('facebook',$social['facebook'] ?? '') }}" placeholder="https://facebook.com/..."></div></div><button class="button button-primary">Simpan Media Sosial</button></form></section>
@endsection
