@extends('layouts.admin')
@section('title','Buku Kas')
@section('page-title','Buku Kas')
@section('page-description','Catatan sederhana untuk uang masuk dan uang keluar.')
@section('content')
@include('partials.admin-page-header')
@php($balance = $cashIn - $cashOut)
<div class="cash-summary"><article><small>Saldo buku kas</small><strong>Rp {{ number_format($balance,0,',','.') }}</strong><span>Per {{ now()->format('d M Y') }}</span></article><article><small>Uang masuk</small><strong class="green">Rp {{ number_format($cashIn,0,',','.') }}</strong><span>Pembayaran verified</span></article><article><small>Uang keluar</small><strong class="red">Rp {{ number_format($cashOut,0,',','.') }}</strong><span>Transaksi keluar</span></article></div>
<section class="admin-card"><div class="admin-card-heading"><div><h2>Riwayat Transaksi</h2><p>Pembayaran terverifikasi tercatat otomatis.</p></div></div><div class="filter-bar"><input placeholder="Cari transaksi atau pesanan"><select><option>Semua jenis</option><option>Uang Masuk</option><option>Uang Keluar</option></select><input type="month" value="{{ now()->format('Y-m') }}"><button class="button button-primary">Terapkan</button></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Tanggal</th><th>Referensi</th><th>Keterangan</th><th>Kategori</th><th>Jenis</th><th>Nominal</th><th>Status</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->created_at->format('d M Y') }}</td><td><b>{{ $entry->reference }}</b></td><td>{{ $entry->note ?: '-' }}</td><td>{{ str($entry->category)->replace('_',' ')->title() }}</td><td><span class="cash-type {{ $entry->direction === 'in' ? 'masuk' : 'keluar' }}">{{ $entry->direction === 'in' ? 'Masuk' : 'Keluar' }}</span></td><td><b>Rp {{ number_format($entry->amount,0,',','.') }}</b></td><td>{{ $entry->reversed_at ? 'Reversal' : 'Aktif' }}</td></tr>@empty<tr><td colspan="7">Belum ada transaksi kas.</td></tr>@endforelse</tbody></table></div>{{ $entries->links() }}</section>
@endsection
