@extends('layouts.admin')
@section('title','Buku Kas')
@section('page-title','Buku Kas Manual')
@section('page-description','Catatan uang masuk dan keluar yang diinput admin.')
@section('page-action')<a href="{{ route('admin.cashbook.export') }}" class="button button-secondary">Export CSV</a>@endsection
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
@if($errors->any())<section class="admin-card">{{ $errors->first() }}</section>@endif
@php($balance = $cashIn - $cashOut)
<div class="cash-summary"><article><small>Saldo buku kas</small><strong>Rp {{ number_format($balance,0,',','.') }}</strong><span>Manual</span></article><article><small>Uang masuk</small><strong class="green">Rp {{ number_format($cashIn,0,',','.') }}</strong><span>Transaksi manual</span></article><article><small>Uang keluar</small><strong class="red">Rp {{ number_format($cashOut,0,',','.') }}</strong><span>Transaksi manual</span></article></div>
<section class="admin-card"><h2>Tambah Transaksi</h2><form method="POST" action="{{ route('admin.cashbook.store') }}" class="form-grid">@csrf<div class="form-group"><label>Tanggal</label><input name="entry_date" type="date" value="{{ now()->format('Y-m-d') }}" required></div><div class="form-group"><label>Jenis</label><select name="direction"><option value="income">Kas masuk</option><option value="expense">Kas keluar</option></select></div><div class="form-group"><label>Kategori</label><input name="category" required></div><div class="form-group"><label>Metode</label><input name="payment_method" placeholder="cash / transfer / qris"></div><div class="form-group"><label>Nominal</label><input name="amount" type="number" min="1" required></div><div class="form-group"><label>Referensi</label><input name="reference"></div><div class="form-group full"><label>Deskripsi</label><textarea name="note"></textarea></div><button class="button button-primary">Simpan Transaksi</button></form></section>
<section class="admin-card"><div class="admin-card-heading"><div><h2>Riwayat Transaksi Manual</h2><p>Pembayaran pesanan tidak otomatis masuk ke buku kas.</p></div></div><form class="filter-bar"><input name="q" value="{{ request('q') }}" placeholder="Cari transaksi"><select name="direction"><option value="">Semua jenis</option><option value="income" @selected(request('direction')==='income')>Kas Masuk</option><option value="expense" @selected(request('direction')==='expense')>Kas Keluar</option></select><input type="date" name="from" value="{{ request('from') }}"><input type="date" name="to" value="{{ request('to') }}"><button class="button button-primary">Terapkan</button></form><div class="table-wrap"><table class="admin-table"><thead><tr><th>Tanggal</th><th>Referensi</th><th>Keterangan</th><th>Kategori</th><th>Jenis</th><th>Nominal</th><th></th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->entry_date?->format('d M Y') }}</td><td><b>{{ $entry->reference }}</b></td><td>{{ $entry->note ?: '-' }}</td><td>{{ $entry->category }}</td><td><span class="cash-type {{ $entry->direction === 'income' ? 'masuk' : 'keluar' }}">{{ $entry->direction === 'income' ? 'Masuk' : 'Keluar' }}</span></td><td><b>Rp {{ number_format($entry->amount,0,',','.') }}</b></td><td><form method="POST" action="{{ route('admin.cashbook.destroy',$entry) }}">@csrf @method('DELETE')<button class="table-link">Arsipkan</button></form></td></tr>@empty<tr><td colspan="7">Belum ada transaksi kas manual.</td></tr>@endforelse</tbody></table></div>{{ $entries->links() }}</section>
@endsection
