@extends('layouts.admin')
@php($editing = $category->exists)
@section('title',$editing ? 'Edit Kategori' : 'Tambah Kategori')
@section('page-title',$editing ? 'Edit Kategori' : 'Tambah Kategori')
@section('page-description','Atur kategori yang tampil pada katalog pelanggan.')
@section('page-action')<a href="{{ route('admin.categories') }}" class="button button-secondary">Kembali</a>@endsection
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
<form class="admin-form-layout" method="POST" action="{{ $editing ? route('admin.categories.update',$category) : route('admin.categories.store') }}" enctype="multipart/form-data">@csrf @if($editing) @method('PUT') @endif<div><section class="admin-card form-section"><div class="form-grid"><div class="form-group"><label>Nama</label><input name="name" value="{{ old('name',$category->name) }}" required></div><div class="form-group"><label>Slug</label><input name="slug" value="{{ old('slug',$category->slug) }}"></div><div class="form-group full"><label>Deskripsi</label><textarea name="description">{{ old('description',$category->description) }}</textarea></div><div class="form-group"><label>Urutan</label><input name="sort_order" type="number" value="{{ old('sort_order',$category->sort_order ?? 0) }}"></div></div></section></div><aside><section class="admin-card"><h2>Gambar Kategori</h2>@if($category->imageUrl())<img src="{{ $category->imageUrl() }}" alt="{{ $category->name }}" style="width:100%;border-radius:8px">@else<div class="admin-upload compact"><b>Belum ada gambar</b></div>@endif<div class="form-group"><label>Upload gambar</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"></div>@if($category->image_path)<label><input name="remove_image" value="1" type="checkbox"> Hapus gambar</label>@endif</section><section class="admin-card"><h2>Status</h2><label><input name="is_active" value="1" type="checkbox" @checked(old('is_active',$category->is_active ?? true))> Aktif</label><label><input name="is_featured" value="1" type="checkbox" @checked(old('is_featured',$category->is_featured))> Unggulan</label></section>@if($errors->any())<section class="admin-card">{{ $errors->first() }}</section>@endif<button class="button button-primary button-block">Simpan Kategori</button></aside></form>
@endsection
