@extends('layouts.admin')
@section('title','Beranda Admin')
@section('page-title','Ringkasan Hari Ini')
@section('page-description','Fokus pada pekerjaan yang perlu segera ditangani.')
@section('content')
@include('partials.admin-page-header')
<div class="stats-grid"><article><span class="stat-icon blue">□</span><div><small>Pesanan baru</small><strong>{{ $newOrdersCount }}</strong><a href="{{ route('admin.orders') }}">Periksa pesanan</a></div></article><article><span class="stat-icon yellow">Rp</span><div><small>Pembayaran diperiksa</small><strong>{{ $pendingPaymentsCount }}</strong><a href="{{ route('admin.orders') }}">Lihat pembayaran</a></div></article><article><span class="stat-icon green">✓</span><div><small>Dalam produksi</small><strong>{{ $productionCount }}</strong><a href="{{ route('admin.orders') }}">Pantau produksi</a></div></article><article><span class="stat-icon red">!</span><div><small>Stok menipis</small><strong>{{ $lowStockCount }}</strong><a href="{{ route('admin.stock') }}">Periksa stok</a></div></article></div>
<div class="admin-grid-main"><section class="admin-card"><div class="admin-card-heading"><div><h2>Perlu Ditangani</h2><p>Urutan pekerjaan berdasarkan prioritas.</p></div><a href="{{ route('admin.orders') }}">Lihat semua</a></div><div class="task-list"><a href="{{ route('admin.orders',['status'=>'payment_review']) }}"><span class="task-dot red"></span><div><b>{{ $pendingPaymentsCount }} bukti pembayaran perlu diperiksa</b><small>Verifikasi bukti sebelum kas dicatat.</small></div><span>Periksa →</span></a><a href="{{ route('admin.orders',['status'=>'pending_review']) }}"><span class="task-dot yellow"></span><div><b>{{ $newOrdersCount }} pesanan menunggu konfirmasi harga</b><small>Periksa spesifikasi dan file desain.</small></div><span>Buka →</span></a><a href="{{ route('admin.stock') }}"><span class="task-dot blue"></span><div><b>{{ $lowStockCount }} bahan mencapai stok minimum</b><small>Tambah stok lewat mutasi masuk.</small></div><span>Lihat →</span></a></div></section><section class="admin-card"><div class="admin-card-heading"><div><h2>Tindakan Cepat</h2><p>Pekerjaan yang sering dilakukan.</p></div></div><div class="quick-actions"><a href="{{ route('admin.products.create') }}"><span>＋</span>Tambah Produk</a><a href="{{ route('admin.stock') }}"><span>↥</span>Tambah Stok</a><a href="{{ route('admin.cashbook') }}"><span>Rp</span>Catat Kas</a><a href="{{ route('admin.appearance') }}"><span>□</span>Ubah Banner</a></div></section></div>
<section class="admin-card"><div class="admin-card-heading"><div><h2>Pesanan Terbaru</h2><p>Lima pesanan yang baru masuk atau diperbarui.</p></div><a href="{{ route('admin.orders') }}">Buka daftar pesanan</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Kode</th><th>Customer</th><th>Produk</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recentOrders as $order)<tr><td>{{ $order->order_number }}</td><td>{{ $order->customer->name }}</td><td>{{ $order->items->pluck('product_name')->join(', ') }}</td><td>{{ $order->final_total === null ? 'Rp '.number_format($order->estimated_total,0,',','.') : 'Rp '.number_format($order->final_total,0,',','.') }}</td><td><span class="status-pill neutral">{{ str($order->status)->replace('_',' ')->title() }}</span></td><td><a class="table-link" href="{{ route('admin.orders.show',$order) }}">Buka</a></td></tr>@empty<tr><td colspan="6">Belum ada pesanan.</td></tr>@endforelse</tbody></table></div></section>
@endsection
