@extends('layouts.admin')
@section('title','Beranda Admin')
@section('page-title','Ringkasan Hari Ini')
@section('page-description','Fokus pada pekerjaan yang perlu segera ditangani.')
@section('content')
@include('partials.admin-page-header')
<div class="stats-grid"><article><span class="stat-icon blue">▤</span><div><small>Pesanan baru</small><strong>8</strong><a href="{{ route('admin.orders') }}">Periksa pesanan</a></div></article><article><span class="stat-icon yellow">Rp</span><div><small>Pembayaran diperiksa</small><strong>3</strong><a href="{{ route('admin.orders') }}">Lihat pembayaran</a></div></article><article><span class="stat-icon green">✓</span><div><small>Dalam produksi</small><strong>12</strong><a href="{{ route('admin.orders') }}">Pantau produksi</a></div></article><article><span class="stat-icon red">!</span><div><small>Stok menipis</small><strong>4</strong><a href="{{ route('admin.stock') }}">Periksa stok</a></div></article></div>
<div class="admin-grid-main"><section class="admin-card"><div class="admin-card-heading"><div><h2>Perlu Ditangani</h2><p>Urutan pekerjaan berdasarkan prioritas.</p></div><a href="{{ route('admin.orders') }}">Lihat semua</a></div><div class="task-list"><a href="{{ route('admin.orders.show') }}"><span class="task-dot red"></span><div><b>3 bukti pembayaran perlu diperiksa</b><small>Pesanan terbaru 12 menit lalu</small></div><span>Periksa →</span></a><a href="{{ route('admin.orders.show') }}"><span class="task-dot yellow"></span><div><b>5 pesanan menunggu konfirmasi harga</b><small>Periksa spesifikasi dan file desain</small></div><span>Buka →</span></a><a href="{{ route('admin.stock') }}"><span class="task-dot blue"></span><div><b>4 bahan mencapai stok minimum</b><small>Vinyl putih tersisa 8 lembar</small></div><span>Lihat →</span></a></div></section><section class="admin-card"><div class="admin-card-heading"><div><h2>Tindakan Cepat</h2><p>Pekerjaan yang sering dilakukan.</p></div></div><div class="quick-actions"><a href="{{ route('admin.products.create') }}"><span>＋</span>Tambah Produk</a><a href="{{ route('admin.stock') }}"><span>↥</span>Tambah Stok</a><a href="{{ route('admin.cashbook') }}"><span>Rp</span>Catat Kas</a><a href="{{ route('admin.appearance') }}"><span>▧</span>Ubah Banner</a></div></section></div>
<section class="admin-card"><div class="admin-card-heading"><div><h2>Pesanan Terbaru</h2><p>Lima pesanan yang baru masuk atau diperbarui.</p></div><a href="{{ route('admin.orders') }}">Buka daftar pesanan</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Kode</th><th>Customer</th><th>Produk</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@foreach([['DMT-240922-A12B','Nadia Putri','Stiker Vinyl','Rp 185.000','Pembayaran Diperiksa','warning'],['DMT-240922-C34D','Fajar Hadi','X-Banner','Rp 240.000','Menunggu Konfirmasi','neutral'],['DMT-240921-E56F','Maya Sari','Kartu Nama','Rp 130.000','Dalam Produksi','info'],['DMT-240921-G78H','Rizki Akbar','Brosur A5','Rp 450.000','Siap Diserahkan','success'],['DMT-240920-I90J','Siti Aminah','Stempel K3','Rp 95.000','Selesai','success']] as $row)<tr>@foreach(array_slice($row,0,4) as $cell)<td>{{ $cell }}</td>@endforeach<td><span class="status-pill {{ $row[5] }}">{{ $row[4] }}</span></td><td><a class="table-link" href="{{ route('admin.orders.show') }}">Buka</a></td></tr>@endforeach</tbody></table></div></section>
@endsection
