@extends('layouts.admin')
@section('title','Detail Pesanan')
@section('page-title',$order->order_number)
@section('page-description','Dibuat '.$order->created_at->format('d M Y, H.i'))
@section('page-action')<div class="cart-actions"><a href="{{ route('admin.orders.invoice',$order) }}" target="_blank" class="button button-primary">Cetak Invoice</a><a href="{{ route('admin.orders') }}" class="button button-secondary">Kembali</a></div>@endsection
@section('content')
@include('partials.admin-page-header')
@php($remaining = max(0, (int) $order->final_total - (int) $order->amount_paid))
<div class="order-admin-status"><span class="status-pill neutral">{{ str($order->status)->replace('_',' ')->title() }}</span></div>
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
<div class="admin-detail-grid"><div><section class="admin-card"><h2>Data Customer</h2><dl class="detail-list"><div><dt>Nama</dt><dd>{{ $order->customer->name }}</dd></div><div><dt>WhatsApp</dt><dd>{{ $order->customer->phone }}</dd></div><div><dt>Email</dt><dd>{{ $order->customer->email ?: '-' }}</dd></div><div><dt>Penerimaan</dt><dd>{{ $order->fulfillment_method === 'shipping' ? 'Pengiriman' : 'Ambil sendiri' }}</dd></div><div class="wide"><dt>Alamat</dt><dd>{{ $order->shipping_address ?: '-' }} {{ $order->shipping_region }}</dd></div></dl></section>
@foreach($order->items as $item)<section class="admin-card"><h2>{{ $item->product_name }}</h2><div class="admin-product-detail"><x-product-image :model="$item" :alt="$item->product_name" class="summary-thumb large" /><div><p>@foreach($item->options as $option){{ $option->option_name }}: {{ $option->option_value }}@if(!$loop->last) | @endif @endforeach</p><dl><div><dt>Jumlah</dt><dd>{{ $item->quantity }} {{ $item->unit }}</dd></div><div><dt>Estimasi</dt><dd>Rp {{ number_format($item->subtotal,0,',','.') }}</dd></div><div><dt>Final</dt><dd>{{ $item->final_subtotal === null ? '-' : 'Rp '.number_format($item->final_subtotal,0,',','.') }}</dd></div><div><dt>Stok</dt><dd>{{ $item->stock_deducted_at ? 'Sudah dipotong' : 'Belum dipotong' }}</dd></div>@foreach($item->files as $file)<div><dt>File desain</dt><dd><a href="{{ route('admin.order-files.download',$file) }}">{{ $file->original_name }}</a></dd></div>@endforeach</dl></div></div></section>@endforeach
<section class="admin-card"><h2>Pembayaran</h2><div class="table-wrap"><table class="admin-table"><thead><tr><th>Metode</th><th>Jenis</th><th>Nominal</th><th>Status</th><th>Bukti</th><th></th></tr></thead><tbody>@forelse($order->payments as $payment)<tr><td>{{ str($payment->method)->replace('_',' ')->title() }}</td><td>{{ str($payment->payment_type)->replace('_',' ')->title() }}</td><td>Rp {{ number_format($payment->amount,0,',','.') }}</td><td>{{ str($payment->status)->title() }}</td><td>@if($payment->hasProofFile())<b>{{ $payment->proof_original_name }}</b><small>{{ $payment->proof_mime_type }} | {{ number_format((int) $payment->proof_size / 1024, 1) }} KB | {{ $payment->created_at->format('d M Y, H.i') }}</small>@if($payment->isProofPreviewable())<a href="{{ route('admin.payments.proof.preview',$payment) }}" target="_blank" class="table-link">Lihat</a>@endif <a href="{{ route('admin.payments.proof.download',$payment) }}" class="table-link">Unduh Bukti</a>@else - @endif</td><td><form method="POST" action="{{ route('admin.payments.verify',$payment) }}">@csrf<button class="table-link">Verifikasi</button></form><form method="POST" action="{{ route('admin.payments.reject',$payment) }}">@csrf<button class="table-link">Tolak</button></form><form method="POST" action="{{ route('admin.payments.cancel-verification',$payment) }}">@csrf<button class="table-link">Batalkan</button></form></td></tr>@empty<tr><td colspan="6">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-card"><h2>Riwayat Status</h2><div class="mini-timeline">@foreach($order->statusHistories as $history)<div class="{{ $loop->last ? 'current' : 'done' }}"><span></span><div><b>{{ str($history->status)->replace('_',' ')->title() }}</b><small>{{ $history->created_at->format('d M Y, H.i') }}</small></div></div>@endforeach</div></section></div>
<aside><section class="admin-card price-card"><h2>Rincian Harga</h2><div><span>Estimasi customer</span><b>Rp {{ number_format($order->estimated_subtotal,0,',','.') }}</b></div><div><span>Ongkir</span><b>Rp {{ number_format($order->shipping_cost,0,',','.') }}</b></div><div class="total"><span>Total estimasi</span><b>Rp {{ number_format($order->estimated_total,0,',','.') }}</b></div><div><span>Harga final</span><b>{{ $order->final_total === null ? 'Belum ditetapkan' : 'Rp '.number_format($order->final_total,0,',','.') }}</b></div><div><span>Dibayar</span><b>Rp {{ number_format($order->amount_paid,0,',','.') }}</b></div><div><span>Sisa</span><b>Rp {{ number_format($remaining,0,',','.') }}</b></div><form method="POST" action="{{ route('admin.orders.price',$order) }}">@csrf<div class="form-group"><label>Harga final</label><input name="final_total" type="number" value="{{ old('final_total',$order->final_total ?? $order->estimated_total) }}"></div><div class="form-group"><label>Ongkir</label><input name="shipping_cost" type="number" value="{{ old('shipping_cost',$order->shipping_cost) }}"></div><div class="form-group"><label>Catatan internal</label><textarea name="internal_note">{{ old('internal_note',$order->internal_note) }}</textarea></div><button class="button button-primary button-block">Simpan Harga</button></form></section><section class="admin-card"><h2>Produksi</h2><form method="POST" action="{{ route('admin.orders.production',$order) }}">@csrf<input type="hidden" name="step" value="start"><button class="button button-primary button-block">Mulai Produksi</button></form><form method="POST" action="{{ route('admin.orders.production',$order) }}">@csrf<input type="hidden" name="step" value="ready"><button class="button button-secondary button-block">Siap Diserahkan</button></form><form method="POST" action="{{ route('admin.orders.production',$order) }}">@csrf<input type="hidden" name="step" value="complete"><button class="button button-secondary button-block">Selesai</button></form></section><section class="admin-card"><h2>Arsip</h2>@if($order->archived_at)<form method="POST" action="{{ route('admin.orders.restore',$order) }}">@csrf<button class="button button-primary button-block">Pulihkan</button></form>@elseif(in_array($order->status, ['completed','cancelled'], true))<form method="POST" action="{{ route('admin.orders.archive',$order) }}" onsubmit="return confirm('Arsipkan pesanan {{ $order->order_number }}? Pesanan akan dipindahkan dari daftar aktif ke Arsip dan tidak dihapus permanen.')">@csrf<button class="button button-secondary button-block">Arsipkan</button></form>@else<p class="muted">Pesanan aktif belum dapat diarsipkan.</p>@endif</section><section class="admin-card"><h2>Catatan Pelanggan</h2><p>{{ $order->customer_note ?: '-' }}</p></section></aside></div>
@endsection
