@extends('layouts.admin')
@section('title','Detail Pesanan') @section('page-title',$order->order_number) @section('page-description','Dibuat '.$order->created_at->format('d M Y, H.i'))
@section('page-action')<a href="{{ route('admin.orders') }}" class="button button-secondary">Kembali</a>@endsection
@section('content') @include('partials.admin-page-header')
<div class="order-admin-status"><span class="status-pill neutral">{{ str($order->status)->replace('_',' ')->title() }}</span></div>
<div class="admin-detail-grid"><div><section class="admin-card"><h2>Data Customer</h2><dl class="detail-list"><div><dt>Nama</dt><dd>{{ $order->customer->name }}</dd></div><div><dt>WhatsApp</dt><dd>{{ $order->customer->phone }}</dd></div><div><dt>Email</dt><dd>{{ $order->customer->email ?: '-' }}</dd></div><div><dt>Penerimaan</dt><dd>{{ $order->fulfillment_method === 'shipping' ? 'Pengiriman' : 'Ambil sendiri' }}</dd></div><div class="wide"><dt>Alamat</dt><dd>{{ $order->shipping_address ?: '-' }} {{ $order->shipping_region }}</dd></div></dl></section>
@foreach($order->items as $item)<section class="admin-card"><h2>{{ $item->product_name }}</h2><div class="admin-product-detail"><span class="summary-thumb large"></span><div><p>@foreach($item->options as $option){{ $option->option_name }}: {{ $option->option_value }}@if(!$loop->last) | @endif @endforeach</p><dl><div><dt>Jumlah</dt><dd>{{ $item->quantity }} {{ $item->unit }}</dd></div><div><dt>Estimasi</dt><dd>Rp {{ number_format($item->subtotal,0,',','.') }}</dd></div>@foreach($item->files as $file)<div><dt>File desain</dt><dd><a href="{{ route('admin.order-files.download',$file) }}">{{ $file->original_name }}</a></dd></div>@endforeach</dl></div></div></section>@endforeach
<section class="admin-card"><h2>Riwayat Status</h2><div class="mini-timeline">@foreach($order->statusHistories as $history)<div class="{{ $loop->last ? 'current' : 'done' }}"><span></span><div><b>{{ str($history->status)->replace('_',' ')->title() }}</b><small>{{ $history->created_at->format('d M Y, H.i') }}</small></div></div>@endforeach</div></section></div>
<aside><section class="admin-card price-card"><h2>Rincian Harga</h2><div><span>Estimasi customer</span><b>Rp {{ number_format($order->estimated_subtotal,0,',','.') }}</b></div><div><span>Ongkir</span><b>Rp {{ number_format($order->shipping_cost,0,',','.') }}</b></div><div class="total"><span>Total estimasi</span><b>Rp {{ number_format($order->estimated_total,0,',','.') }}</b></div><div><span>Harga final</span><b>{{ $order->final_total === null ? 'Belum ditetapkan' : 'Rp '.number_format($order->final_total,0,',','.') }}</b></div></section><section class="admin-card"><h2>Catatan Pelanggan</h2><p>{{ $order->customer_note ?: '-' }}</p></section></aside></div>@endsection
