@extends('layouts.admin')
@php($editing = $product->exists)
@section('title',$editing ? 'Edit Produk' : 'Tambah Produk')
@section('page-title',$editing ? 'Edit Produk' : 'Tambah Produk')
@section('page-description','Isi informasi produk secara bertahap dan jelas.')
@section('page-action')<a href="{{ route('admin.products') }}" class="button button-secondary">Batal</a>@endsection
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
<form class="admin-form-layout" method="POST" action="{{ $editing ? route('admin.products.update',$product) : route('admin.products.store') }}" enctype="multipart/form-data">
    @csrf
    @if($editing) @method('PATCH') @endif
    <div>
        <section class="admin-card form-section"><div class="form-section-heading"><span>1</span><div><h2>Informasi Dasar</h2><p>Nama dan penjelasan yang dilihat customer.</p></div></div><div class="form-grid"><div class="form-group"><label>Nama produk</label><input name="name" value="{{ old('name',$product->name) }}" required></div><div class="form-group"><label>Slug</label><input name="slug" value="{{ old('slug',$product->slug) }}"></div><div class="form-group"><label>Kategori</label><select name="category_id" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('category_id',$product->category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="form-group"><label>SKU</label><input name="sku" value="{{ old('sku',$product->sku) }}"></div><div class="form-group"><label>Tag</label><input name="tag" value="{{ old('tag',$product->tag) }}"></div><div class="form-group full"><label>Deskripsi singkat</label><input name="short_description" value="{{ old('short_description',$product->short_description) }}"></div><div class="form-group full"><label>Deskripsi lengkap</label><textarea name="description" rows="5">{{ old('description',$product->description) }}</textarea></div></div></section>
        <section class="admin-card form-section"><div class="form-section-heading"><span>2</span><div><h2>Harga, Stok, dan Produksi</h2><p>Tentukan dasar perhitungan estimasi.</p></div></div><div class="form-grid"><div class="form-group"><label>Harga dasar</label><div class="input-prefix"><span>Rp</span><input name="base_price" type="number" value="{{ old('base_price',$product->base_price) }}" required></div></div><div class="form-group"><label>Minimum order</label><input name="minimum_order" type="number" value="{{ old('minimum_order',$product->minimum_order ?? 1) }}" required></div><div class="form-group"><label>Satuan</label><input name="unit" value="{{ old('unit',$product->unit) }}" required></div><div class="form-group"><label>Stok saat ini</label><input name="stock_on_hand" type="number" value="{{ old('stock_on_hand',$product->stock_on_hand ?? 0) }}" required></div><div class="form-group"><label>Stok minimum</label><input name="stock_minimum" type="number" value="{{ old('stock_minimum',$product->stock_minimum ?? 0) }}" required></div><div class="form-group"><label>Urutan</label><input name="sort_order" type="number" value="{{ old('sort_order',$product->sort_order ?? 0) }}" required></div><div class="form-group"><label>Tone</label><select name="tone"><option value="blue" @selected(old('tone',$product->tone)==='blue')>Blue</option><option value="cyan" @selected(old('tone',$product->tone)==='cyan')>Cyan</option><option value="navy" @selected(old('tone',$product->tone)==='navy')>Navy</option><option value="yellow" @selected(old('tone',$product->tone)==='yellow')>Yellow</option><option value="green" @selected(old('tone',$product->tone)==='green')>Green</option></select></div><div class="form-group full"><label>Estimasi pengerjaan</label><input name="production_estimate" value="{{ old('production_estimate',$product->production_estimate) }}"></div></div></section>
    </div>
    <aside><section class="admin-card"><h2>Gambar Produk</h2><div class="product-form-preview"><x-product-image :model="$product" :alt="$product->name ?: 'Gambar produk'" /></div><div class="form-group"><label>Ganti gambar</label><input name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, WebP maks. 4 MB</small></div>@if($product->image_path)<label><input name="remove_image" value="1" type="checkbox"> Hapus gambar</label>@endif</section><section class="admin-card"><h2>Status</h2><label class="switch-row"><span><b>Produk aktif</b><small>Tampil pada katalog customer</small></span><input name="is_active" value="1" type="checkbox" @checked(old('is_active',$product->is_active ?? true))></label><label class="switch-row"><span><b>Produk unggulan</b><small>Tampil pada beranda</small></span><input name="is_featured" value="1" type="checkbox" @checked(old('is_featured',$product->is_featured))></label></section>@if($errors->any())<section class="admin-card"><h2>Periksa Input</h2><p>{{ $errors->first() }}</p></section>@endif<button class="button button-primary button-block">Simpan Produk</button></aside>
</form>
@endsection
