@extends('layouts.admin')
@section('title','Produk & Stok')
@section('page-title','Produk & Stok')
@section('page-description','Kelola katalog, harga dasar, dan ketersediaan bahan.')
@section('page-action')<a href="{{ route('admin.products.create') }}" class="button button-primary">Tambah Produk</a>@endsection
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
<div class="admin-tabs"><a class="active" href="{{ route('admin.products') }}">Produk</a><a href="{{ route('admin.stock') }}">Stok Bahan</a><a href="{{ route('admin.categories') }}">Kategori ({{ $categories->count() }})</a></div>
<section class="admin-card"><form class="filter-bar"><input name="q" value="{{ request('q') }}" placeholder="Cari nama produk"><select name="category_id"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) request('category_id') === $category->id)>{{ $category->name }}</option>@endforeach</select><select name="status"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Nonaktif</option></select><button class="button button-primary">Terapkan</button></form><div class="table-wrap"><table class="admin-table admin-products-table"><thead><tr><th>Produk</th><th>Kategori</th><th>Harga Mulai</th><th>Min. Order</th><th>Stok</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($products as $product)<tr><td><div class="admin-product-cell"><x-product-image :model="$product" :alt="$product->name" class="admin-product-thumb" /><div class="admin-product-info"><span class="admin-product-name">{{ $product->name }}</span>@if($product->sku)<small class="admin-product-sku">{{ $product->sku }}</small>@endif</div></div></td><td class="admin-category-col"><span class="admin-category-text">{{ $product->category?->name ?? '-' }}</span></td><td class="admin-price-col">Rp {{ number_format($product->base_price, 0, ',', '.') }}</td><td class="admin-min-col">{{ $product->minimum_order }} {{ $product->unit }}</td><td class="admin-stock-col"><b>{{ $product->stock_on_hand }}</b> {{ $product->unit }}</td><td class="admin-status-col"><span class="status-pill {{ $product->is_active ? 'success' : 'neutral' }}">{{ $product->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="admin-actions-col"><div class="admin-row-actions"><a href="{{ route('admin.products.edit',$product) }}" class="table-link">Edit</a><form method="POST" action="{{ route('admin.products.destroy',$product) }}">@csrf @method('DELETE')<button class="table-link danger-link">{{ $product->is_active ? 'Nonaktifkan' : 'Nonaktif' }}</button></form></div></td></tr>@empty<tr><td colspan="7">Belum ada produk.</td></tr>@endforelse</tbody></table></div>{{ $products->links() }}</section>
@endsection
