@extends('layouts.admin')
@section('title','Pengaturan')
@section('page-title','Pengaturan')
@section('page-description','Kelola profil, keamanan akun, dan staf admin.')
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
@if($errors->any())<section class="admin-card">{{ $errors->first() }}</section>@endif
<div class="settings-grid">
    <section class="admin-card"><h2>Profil Saya</h2><div class="form-grid"><div class="form-group"><label>Nama</label><input value="{{ auth()->user()->name }}" disabled></div><div class="form-group"><label>Email</label><input value="{{ auth()->user()->email }}" disabled></div></div></section>
    <section class="admin-card"><h2>Tambah Admin</h2><form method="POST" action="{{ route('admin.admins.store') }}">@csrf<div class="form-grid"><div class="form-group"><label>Nama</label><input name="name" required></div><div class="form-group"><label>Email</label><input name="email" type="email" required></div><div class="form-group"><label>Peran</label><select name="role"><option value="admin">Admin</option><option value="production">Produksi</option><option value="finance">Finance</option><option value="owner">Owner</option></select></div><div class="form-group"><label>Password awal</label><input name="password" type="password" required></div></div><button class="button button-primary">Tambah Admin</button></form></section>
    <section class="admin-card wide"><div class="admin-card-heading"><div><h2>Akun Admin</h2><p>Admin nonaktif tidak dapat masuk dashboard.</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Nama</th><th>Email</th><th>Peran</th><th>Status</th><th>Login terakhir</th><th></th></tr></thead><tbody>@foreach($admins as $admin)<tr><td><b>{{ $admin->name }}</b></td><td>{{ $admin->email }}</td><td>{{ str($admin->role)->title() }}</td><td><span class="status-pill {{ $admin->is_active ? 'success' : 'neutral' }}">{{ $admin->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td>{{ $admin->last_login_at?->format('d M Y, H.i') ?: '-' }}</td><td><form method="POST" action="{{ route('admin.admins.update',$admin) }}">@csrf @method('PATCH')<input name="name" value="{{ $admin->name }}"><input name="email" value="{{ $admin->email }}"><select name="role"><option value="admin" @selected($admin->role === 'admin')>Admin</option><option value="production" @selected($admin->role === 'production')>Produksi</option><option value="finance" @selected($admin->role === 'finance')>Finance</option><option value="owner" @selected($admin->role === 'owner')>Owner</option></select><label><input name="is_active" value="1" type="checkbox" @checked($admin->is_active)> Aktif</label><button class="table-link">Simpan</button></form>@if($admin->id !== auth()->id())<form method="POST" action="{{ route('admin.admins.destroy',$admin) }}">@csrf @method('DELETE')<button class="table-link">Nonaktifkan</button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
</div>
@endsection
