@extends('layouts.admin')
@section('title','Stok Bahan')
@section('page-title','Produk & Stok')
@section('page-description','Pantau stok dan catat setiap perubahan bahan.')
@section('content')
@include('partials.admin-page-header')
@if(session('status'))<section class="admin-card">{{ session('status') }}</section>@endif
<div class="admin-tabs"><a href="{{ route('admin.products') }}">Produk</a><a class="active" href="{{ route('admin.stock') }}">Stok Bahan</a><a href="{{ route('admin.categories') }}">Kategori</a></div>
@if($lowStockCount > 0)<div class="stock-alert">{{ $lowStockCount }} produk telah mencapai stok minimum. Segera lakukan penambahan stok.</div>@endif
<section class="admin-card"><div class="filter-bar"><input placeholder="Cari bahan"><select><option>Semua kondisi</option><option>Stok menipis</option><option>Stok aman</option></select><button class="button button-primary">Terapkan</button></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Produk</th><th>Stok saat ini</th><th>Stok minimum</th><th>Kondisi</th><th>Mutasi</th><th></th></tr></thead><tbody>@forelse($products as $product)<tr><td><b>{{ $product->name }}</b><small>{{ $product->sku }}</small></td><td><b>{{ $product->stock_on_hand }} {{ $product->unit }}</b></td><td>{{ $product->stock_minimum }} {{ $product->unit }}</td><td><span class="status-pill {{ $product->stock_on_hand <= $product->stock_minimum ? 'danger' : 'success' }}">{{ $product->stock_on_hand <= $product->stock_minimum ? 'Menipis' : 'Aman' }}</span></td><td><form method="POST" action="{{ route('admin.stock.adjust',$product) }}">@csrf<input name="quantity" type="number" placeholder="+10 / -2"><input name="note" placeholder="Catatan"><button class="table-link">Simpan</button></form></td><td>{{ $product->inventory_movements_max_created_at ? \Illuminate\Support\Carbon::parse($product->inventory_movements_max_created_at)->format('d M Y, H.i') : '-' }}</td></tr>@empty<tr><td colspan="6">Belum ada produk.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-card"><div class="admin-card-heading"><div><h2>Riwayat Mutasi</h2><p>Termasuk pemakaian otomatis dari pesanan produksi.</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Waktu</th><th>Produk</th><th>Jenis</th><th>Qty</th><th>Saldo</th><th>Catatan</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->created_at->format('d M Y, H.i') }}</td><td>{{ $movement->product->name }}</td><td>{{ str($movement->type)->replace('_',' ')->title() }}</td><td>{{ $movement->quantity }}</td><td>{{ $movement->balance_after }}</td><td>{{ $movement->note ?: '-' }}</td></tr>@empty<tr><td colspan="6">Belum ada mutasi.</td></tr>@endforelse</tbody></table></div></section>
@endsection
