<?php $__env->startSection('title','Keranjang - DMT Print'); ?>
<?php $__env->startSection('breadcrumb'); ?><a href="<?php echo e(route('home')); ?>">Beranda</a><span>></span><b>Keranjang</b><?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?> <?php echo $__env->make('partials.checkout-steps',['activeStep'=>0], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="page-section compact-top"><div class="site-container"><h1 class="page-title">Daftar Belanja</h1>
<?php if(session('success')): ?><p><?php echo e(session('success')); ?></p><?php endif; ?> <?php if($errors->any()): ?><p role="alert"><?php echo e($errors->first()); ?></p><?php endif; ?>
<?php if($items->isEmpty()): ?><section class="panel"><h2>Keranjang masih kosong</h2><p>Pilih produk cetak yang Anda perlukan dari katalog.</p><a href="<?php echo e(route('catalog')); ?>" class="button button-primary">Lihat Katalog</a></section>
<?php else: ?><div class="cart-table"><div class="cart-head"><span>Produk</span><span>Harga</span><span>Jumlah</span><span>Total</span></div>
<?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cart-row"><div class="cart-product"><form method="POST" action="<?php echo e(route('cart.destroy', $item['key'])); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button type="submit" class="remove-item" aria-label="Hapus">x</button></form><span class="cart-thumb"></span><div><b><?php echo e($item['product']->name); ?></b><small><?php $__currentLoopData = $item['price']['values']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php echo e($value['option_name']); ?>: <?php echo e($value['option_value']); ?><?php if(!$loop->last): ?> | <?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></small></div></div><span>Rp <?php echo e(number_format($item['price']['unit_estimate'],0,',','.')); ?></span><form method="POST" action="<?php echo e(route('cart.update',$item['key'])); ?>" class="qty-control small"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><input type="number" name="quantity" min="<?php echo e($item['product']->minimum_order); ?>" value="<?php echo e($item['quantity']); ?>"><button type="submit" aria-label="Perbarui">OK</button></form><b>Rp <?php echo e(number_format($item['price']['subtotal'],0,',','.')); ?></b></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<div class="cart-summary"><div><span>Total estimasi</span><strong>Rp <?php echo e(number_format($subtotal,0,',','.')); ?></strong></div><div class="cart-actions"><a href="<?php echo e(route('catalog')); ?>" class="button button-secondary">Lanjutkan Belanja</a><a href="<?php echo e(route('checkout.recipient')); ?>" class="button button-primary">Lanjutkan</a></div></div><?php endif; ?></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.customer', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\WEB\Laravel\print\dmt\resources\views/customer/cart-dynamic.blade.php ENDPATH**/ ?>