<?php $__env->startSection('title','Detail Pesanan'); ?> <?php $__env->startSection('page-title',$order->order_number); ?> <?php $__env->startSection('page-description','Dibuat '.$order->created_at->format('d M Y, H.i')); ?>
<?php $__env->startSection('page-action'); ?><a href="<?php echo e(route('admin.orders')); ?>" class="button button-secondary">Kembali</a><?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?> <?php echo $__env->make('partials.admin-page-header', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<div class="order-admin-status"><span class="status-pill neutral"><?php echo e(str($order->status)->replace('_',' ')->title()); ?></span></div>
<div class="admin-detail-grid"><div><section class="admin-card"><h2>Data Customer</h2><dl class="detail-list"><div><dt>Nama</dt><dd><?php echo e($order->customer->name); ?></dd></div><div><dt>WhatsApp</dt><dd><?php echo e($order->customer->phone); ?></dd></div><div><dt>Email</dt><dd><?php echo e($order->customer->email ?: '-'); ?></dd></div><div><dt>Penerimaan</dt><dd><?php echo e($order->fulfillment_method === 'shipping' ? 'Pengiriman' : 'Ambil sendiri'); ?></dd></div><div class="wide"><dt>Alamat</dt><dd><?php echo e($order->shipping_address ?: '-'); ?> <?php echo e($order->shipping_region); ?></dd></div></dl></section>
<?php $__currentLoopData = $order->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><section class="admin-card"><h2><?php echo e($item->product_name); ?></h2><div class="admin-product-detail"><span class="summary-thumb large"></span><div><p><?php $__currentLoopData = $item->options; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $option): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php echo e($option->option_name); ?>: <?php echo e($option->option_value); ?><?php if(!$loop->last): ?> | <?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></p><dl><div><dt>Jumlah</dt><dd><?php echo e($item->quantity); ?> <?php echo e($item->unit); ?></dd></div><div><dt>Estimasi</dt><dd>Rp <?php echo e(number_format($item->subtotal,0,',','.')); ?></dd></div><?php $__currentLoopData = $item->files; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $file): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div><dt>File desain</dt><dd><a href="<?php echo e(route('admin.order-files.download',$file)); ?>"><?php echo e($file->original_name); ?></a></dd></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></dl></div></div></section><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<section class="admin-card"><h2>Riwayat Status</h2><div class="mini-timeline"><?php $__currentLoopData = $order->statusHistories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $history): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="<?php echo e($loop->last ? 'current' : 'done'); ?>"><span></span><div><b><?php echo e(str($history->status)->replace('_',' ')->title()); ?></b><small><?php echo e($history->created_at->format('d M Y, H.i')); ?></small></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section></div>
<aside><section class="admin-card price-card"><h2>Rincian Harga</h2><div><span>Estimasi customer</span><b>Rp <?php echo e(number_format($order->estimated_subtotal,0,',','.')); ?></b></div><div><span>Ongkir</span><b>Rp <?php echo e(number_format($order->shipping_cost,0,',','.')); ?></b></div><div class="total"><span>Total estimasi</span><b>Rp <?php echo e(number_format($order->estimated_total,0,',','.')); ?></b></div><div><span>Harga final</span><b><?php echo e($order->final_total === null ? 'Belum ditetapkan' : 'Rp '.number_format($order->final_total,0,',','.')); ?></b></div></section><section class="admin-card"><h2>Catatan Pelanggan</h2><p><?php echo e($order->customer_note ?: '-'); ?></p></section></aside></div><?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\WEB\Laravel\print\dmt\resources\views/admin/order-detail-dynamic.blade.php ENDPATH**/ ?>