<?php $__env->startSection('title','Detail Penerima - DMT Print'); ?>
<?php $__env->startSection('breadcrumb'); ?><a href="<?php echo e(route('home')); ?>">Beranda</a><span>></span><b>Detail Penerima</b><?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?> <?php echo $__env->make('partials.checkout-steps',['activeStep'=>2], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="page-section compact-top"><form class="site-container checkout-grid" method="POST" action="<?php echo e(route('checkout.store')); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?>
<div class="checkout-main"><section class="panel accent-panel"><div class="panel-heading"><div><h2>Detail Penerima</h2><p>Admin akan menghubungi nomor ini untuk konfirmasi.</p></div></div>
<?php if($errors->any()): ?><p role="alert"><?php echo e($errors->first()); ?></p><?php endif; ?><div class="form-grid"><div class="form-group"><label>Nama lengkap</label><input name="name" value="<?php echo e(old('name')); ?>" required></div><div class="form-group"><label>Nomor WhatsApp</label><input name="phone" value="<?php echo e(old('phone')); ?>" required></div><div class="form-group full"><label>Email <small>(opsional)</small></label><input type="email" name="email" value="<?php echo e(old('email')); ?>"></div><div class="form-group full"><label>Catatan</label><textarea name="customer_note"><?php echo e(old('customer_note')); ?></textarea></div></div></section>
<section class="panel accent-panel"><h2>Cara menerima pesanan</h2><div class="choice-cards"><label class="choice-card"><input type="radio" name="fulfillment_method" value="shipping" checked> Pengiriman</label><label class="choice-card"><input type="radio" name="fulfillment_method" value="pickup"> Ambil sendiri</label></div><div class="form-grid"><div class="form-group full"><label>Alamat lengkap</label><textarea name="shipping_address"><?php echo e(old('shipping_address')); ?></textarea></div><div class="form-group"><label>Kota/kabupaten</label><input name="shipping_region" value="<?php echo e(old('shipping_region')); ?>"></div><div class="form-group"><label>Kode pos</label><input name="postal_code" value="<?php echo e(old('postal_code')); ?>"></div><div class="form-group full"><label>Catatan alamat</label><input name="address_note" value="<?php echo e(old('address_note')); ?>"></div></div></section>
<section class="panel"><h2>File desain</h2><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="form-group"><label><?php echo e($item['product']->name); ?> <small>(opsional)</small></label><input type="file" name="design_files[<?php echo e($item['key']); ?>]" accept=".jpg,.jpeg,.png,.pdf,.zip"></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></section>
<label class="check-row"><input type="checkbox" name="approved" value="1" required> Saya memahami harga ini masih estimasi dan harga final ditentukan admin setelah pemeriksaan.</label><button type="submit" class="button button-primary button-block">Buat Pesanan</button></div>
<aside class="checkout-side"><section class="panel sticky-panel"><h2>Ringkasan</h2><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="summary-product"><span class="summary-thumb"></span><div><b><?php echo e($item['product']->name); ?></b><small><?php echo e($item['quantity']); ?> <?php echo e($item['product']->unit); ?> | Rp <?php echo e(number_format($item['price']['subtotal'],0,',','.')); ?></small></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><div class="summary-line total"><span>Total estimasi</span><b>Rp <?php echo e(number_format($subtotal,0,',','.')); ?></b></div><p>Pembayaran dilakukan setelah admin menetapkan harga final.</p></section></aside></form></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.customer', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\WEB\Laravel\print\dmt\resources\views/customer/checkout-order.blade.php ENDPATH**/ ?>