@extends('layouts.customer')
@section('title','Keranjang - DMT Print')
@section('breadcrumb')<a href="{{ route('home') }}">Beranda</a><span>></span><b>Keranjang</b>@endsection
@section('content') @include('partials.checkout-steps',['activeStep'=>0])
<section class="page-section compact-top"><div class="site-container"><h1 class="page-title">Daftar Belanja</h1>
@if(session('success'))<p>{{ session('success') }}</p>@endif @if($errors->any())<p role="alert">{{ $errors->first() }}</p>@endif
@if($items->isEmpty())<section class="panel"><h2>Keranjang masih kosong</h2><p>Pilih produk cetak yang Anda perlukan dari katalog.</p><a href="{{ route('catalog') }}" class="button button-primary">Lihat Katalog</a></section>
@else<div class="cart-table cart-table-refined"><div class="cart-head"><span>Produk</span><span>Harga</span><span>Jumlah</span><span>Total</span></div>
@foreach($items as $item)<div class="cart-row cart-row-refined"><div class="cart-product cart-product-refined"><x-product-image :model="$item['product']" :alt="$item['product']->name" class="cart-thumb" /><div class="cart-product-info"><b>{{ $item['product']->name }}</b><div class="cart-options">@forelse($item['price']['values'] as $value)<span>{{ $value['option_name'] }}: {{ $value['option_value'] }}</span>@empty<span>Tanpa opsi tambahan</span>@endforelse</div><form method="POST" action="{{ route('cart.destroy', $item['key']) }}">@csrf @method('DELETE')<button type="submit" class="remove-item">Hapus</button></form></div></div><div class="cart-price-block"><small>Harga</small><span>Rp {{ number_format($item['price']['unit_estimate'],0,',','.') }}</span></div><form method="POST" action="{{ route('cart.update',$item['key']) }}" class="cart-qty-form">@csrf @method('PATCH')<small>Jumlah</small><div class="qty-control small"><button type="button" data-qty-minus aria-label="Kurangi jumlah">-</button><input data-qty type="number" name="quantity" min="{{ $item['product']->minimum_order }}" value="{{ $item['quantity'] }}"><button type="button" data-qty-plus aria-label="Tambah jumlah">+</button><button type="submit" class="qty-update-button" aria-label="Perbarui jumlah">OK</button></div></form><div class="cart-total-block"><small>Total</small><b>Rp {{ number_format($item['price']['subtotal'],0,',','.') }}</b></div></div>@endforeach</div>
<div class="cart-summary"><div><span>Total estimasi</span><strong>Rp {{ number_format($subtotal,0,',','.') }}</strong></div><div class="cart-actions"><a href="{{ route('catalog') }}" class="button button-secondary">Lanjutkan Belanja</a><a href="{{ route('checkout.recipient') }}" class="button button-primary">Lanjutkan</a></div></div>@endif</div></section>
@endsection
