@extends('layouts.customer')
@section('title','Detail Penerima - DMT Print')
@section('breadcrumb')<a href="{{ route('home') }}">Beranda</a><span>></span><b>Detail Penerima</b>@endsection
@section('content') @include('partials.checkout-steps',['activeStep'=>2])
<section class="page-section compact-top"><form class="site-container checkout-grid" method="POST" action="{{ route('checkout.store') }}" enctype="multipart/form-data">@csrf
<div class="checkout-main"><section class="panel accent-panel"><div class="panel-heading"><div><h2>Detail Penerima</h2><p>Admin akan menghubungi nomor ini untuk konfirmasi.</p></div></div>
@if($errors->any())<p role="alert">{{ $errors->first() }}</p>@endif<div class="form-grid"><div class="form-group"><label>Nama lengkap</label><input name="name" value="{{ old('name') }}" required></div><div class="form-group"><label>Nomor WhatsApp</label><input name="phone" value="{{ old('phone') }}" required></div><div class="form-group full"><label>Email <small>(opsional)</small></label><input type="email" name="email" value="{{ old('email') }}"></div><div class="form-group full"><label>Catatan</label><textarea name="customer_note">{{ old('customer_note') }}</textarea></div></div></section>
<section class="panel accent-panel"><h2>Cara menerima pesanan</h2><div class="choice-cards"><label class="choice-card"><input type="radio" name="fulfillment_method" value="shipping" checked> Pengiriman</label><label class="choice-card"><input type="radio" name="fulfillment_method" value="pickup"> Ambil sendiri</label></div><div class="form-grid"><div class="form-group full"><label>Alamat lengkap</label><textarea name="shipping_address">{{ old('shipping_address') }}</textarea></div><div class="form-group"><label>Kota/kabupaten</label><input name="shipping_region" value="{{ old('shipping_region') }}"></div><div class="form-group"><label>Kode pos</label><input name="postal_code" value="{{ old('postal_code') }}"></div><div class="form-group full"><label>Catatan alamat</label><input name="address_note" value="{{ old('address_note') }}"></div></div></section>
<section class="panel"><h2>File desain</h2>@foreach($items as $item)<div class="form-group"><label>{{ $item['product']->name }} <small>(opsional)</small></label><input type="file" name="design_files[{{ $item['key'] }}]" accept=".jpg,.jpeg,.png,.pdf,.zip"></div>@endforeach</section>
<label class="check-row"><input type="checkbox" name="approved" value="1" required> Saya memahami harga ini masih estimasi dan harga final ditentukan admin setelah pemeriksaan.</label><button type="submit" class="button button-primary button-block">Buat Pesanan</button></div>
<aside class="checkout-side"><section class="panel sticky-panel"><h2>Ringkasan</h2>@foreach($items as $item)<div class="summary-product"><x-product-image :model="$item['product']" :alt="$item['product']->name" class="summary-thumb" /><div><b>{{ $item['product']->name }}</b><small>@foreach($item['price']['values'] as $value){{ $value['option_name'] }}: {{ $value['option_value'] }}@if(!$loop->last) | @endif @endforeach<br>{{ $item['quantity'] }} {{ $item['product']->unit }} | Rp {{ number_format($item['price']['subtotal'],0,',','.') }}</small></div></div>@endforeach<div class="summary-line total"><span>Total estimasi</span><b>Rp {{ number_format($subtotal,0,',','.') }}</b></div><p>Pembayaran dilakukan setelah admin menetapkan harga final.</p></section></aside></form></section>
@endsection
