@extends('layouts.customer')
@section('title', 'DMT Print - Digital Printing')
@section('content')
<section class="hero-slider" data-slider>
    @forelse($banners as $banner)
    <article class="hero-slide {{ $loop->first ? 'active' : '' }}"><div class="site-container hero-grid"><div><p class="eyebrow">Cetak cepat & rapi</p><h1>{{ $banner->title }}</h1><p>{{ $banner->description }}</p>@if($banner->button_label)<a href="{{ $banner->button_url ?: route('catalog') }}" class="button button-yellow">{{ $banner->button_label }}</a>@endif</div><div class="hero-art">@if($banner->imageUrl())<img src="{{ $banner->imageUrl() }}" alt="{{ $banner->title }}">@else<span class="mock-phone">DMT<br><b>PRINT</b></span><span class="mock-box">Paket<br>Cetak</span>@endif</div></div></article>
    @empty
    <article class="hero-slide active"><div class="site-container hero-grid"><div><p class="eyebrow">Cetak cepat & rapi</p><h1>Semua kebutuhan cetak dalam satu tempat</h1><p>Mulai dari stiker, banner, kartu nama, hingga merchandise custom untuk usaha dan acara Anda.</p><a href="{{ route('catalog') }}" class="button button-yellow">Lihat Katalog</a></div><div class="hero-art"><span class="mock-phone">DMT<br><b>PRINT</b></span><span class="mock-box">Paket<br>Cetak</span><span class="mock-card">PROMO<br><b>HEMAT</b></span></div></div></article>
    @endforelse
    <article class="hero-slide"><div class="site-container hero-grid"><div><p class="eyebrow">Untuk UMKM</p><h1>Kemasan menarik, produk makin dipercaya</h1><p>Label, stiker, paper bag, dan materi promosi yang disesuaikan dengan brand Anda.</p><a href="{{ route('catalog') }}" class="button button-yellow">Pilih Produk</a></div><div class="hero-art variant"><span class="mock-box">UMKM</span><span class="mock-card">LABEL<br><b>CUSTOM</b></span></div></div></article>
    <div class="slider-dots">@foreach($banners->isNotEmpty() ? $banners : collect([1]) as $i => $banner)<button class="{{ $loop->first ? 'active' : '' }}" data-slide="{{ $i }}" aria-label="Banner {{ $loop->iteration }}"></button>@endforeach</div>
</section>
<section class="category-strip"><div class="site-container category-list">
    @foreach($categories as $i => $category)<a href="{{ route('catalog', ['category' => $category->slug]) }}" class="category-item"><span class="category-icon icon-shape-{{ ($i % 4)+1 }}"></span><span>{{ $category->name }}</span></a>@endforeach
</div></section>
<section class="page-section"><div class="site-container"><div class="section-heading"><div><p class="eyebrow blue">Pilihan populer</p><h2>Produk unggulan</h2></div><a href="{{ route('catalog') }}">Lihat semua <span>→</span></a></div><div class="product-grid">@foreach($products->take(4) as $product) @include('partials.product-card', ['product'=>$product]) @endforeach</div></div></section>
<section class="promo-band"><div class="site-container promo-band-grid"><div class="promo-poster"><small>DMT PRINT</small><strong>CETAK<br>UNTUK<br>USAHA</strong><span>Harga bersahabat</span></div><div><p class="eyebrow">Solusi UMKM</p><h2>Buat brand Anda tampil lebih profesional</h2><p>Siapkan kebutuhan promosi dan kemasan dengan pilihan bahan, ukuran, dan finishing yang fleksibel.</p><div class="benefit-row"><span><b>01</b>Konsultasi produk</span><span><b>02</b>Estimasi transparan</span><span><b>03</b>Pengerjaan terpantau</span></div><a href="{{ route('catalog') }}" class="button button-primary">Jelajahi Produk</a></div></div></section>
<section class="page-section"><div class="site-container"><div class="section-heading"><div><p class="eyebrow blue">Lengkapi kebutuhan Anda</p><h2>Produk lainnya</h2></div></div><div class="product-grid">@foreach($products->skip(4)->take(4) as $product) @include('partials.product-card', ['product'=>$product]) @endforeach</div></div></section>
<section class="how-section"><div class="site-container"><div class="section-heading centered"><div><p class="eyebrow blue">Mudah dan jelas</p><h2>Cara memesan</h2></div></div><div class="steps-grid"><article><span>1</span><h3>Pilih produk</h3><p>Tentukan ukuran, bahan, finishing, dan jumlah.</p></article><article><span>2</span><h3>Kirim detail</h3><p>Isi data serta unggah desain atau tautan file.</p></article><article><span>3</span><h3>Konfirmasi harga</h3><p>Admin memeriksa dan menetapkan harga final.</p></article><article><span>4</span><h3>Produksi</h3><p>Pantau status sampai siap diambil atau dikirim.</p></article></div></div></section>
@endsection
